### ISSUE TITLE
merken/sperren

### ISSUE THREAD

**Issue by UlriekeDieterle** [Itprojectthies/partnerboerse2000#5]
Profile sollen per Selektion von Merk-/Sperrliste entfernt oder hinzugefügt werden können

**Comment by ChristopherFunke** [comment]
im Editor kann man bei den "suchergebnissen", wenn man auf ein profil klickt es merken. Die "merkliste" wird auch angezeigt wenn man das in der navbar auswählt. mehr geht leider gerade noch nicht
